name: perdream-init

# on:
#   push:
#     branches: [ release ]
#   pull_request:
#     branches: [ release ]
on: [push]

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1.4.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Publish to NPM
        run: npm publish || true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          NODE_AUTH_TOKEN: ${{ secrets.PERDREAM_INIT_AUTO_PUBLISH_NPM_SECRET }}
